language: node_js
sudo: required
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
env:
  - NODE_ENV=travis
before_install:
  - gem update --system
  - gem install sass --version "=3.3.7"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/249daf9851ea4776f34e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

script:
  - npm run lint
